#!/usr/bin/env bash
# BASH SCRIPT TO Install nginx web server
# AND
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.

sudo apt-get update

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/redirect_me

echo "This page has been moved permanently." | sudo tee /var/www/html/redirect_me/index.html

echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 /redirect_me/index.html;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me.conf

sudo rm -f /etc/nginx/sites-enabled/redirect_me.conf

sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/redirect_me.conf
sudo nginx -t
sudo systemctl restart nginx
