#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
apt-get update
apt-get -y install haproxy
config="
frontend zineddine-frontend
        bind *:80
        mode http
        default_backend zineddine-backend

backend zineddine-backend
        balance roundrobin
        server web-01 100.25.22.28:80 check
        server web-02 100.26.226.197:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy restart
