#!/usr/bin/env bash
# prints "bad luck" 4th iteration, "good luck" on the 8th iteration, and "Holberton School" for other iterations
x=1

while [ $x -le 20 ]
do
    echo $x
    case $x in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    x=$(( x + 1 ))
done
