#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
h=0

while [ $h -le 12 ]
do
    echo "h: $h"
    minute=1
    while [ $minute -le 59 ]
    do
        echo $minute
        minute=$(( minute + 1 ))
    done
    h=$(( h + 1 ))
done
